development:
  cloud_name: dmndhddgf
  api_key: 441468599427583
  api_secret: YFs0xA-5zH0irPjc6LBH5XrUqws
  secure: true
  cdn_subdomain: true

test:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_api_secret
  secure: true
  cdn_subdomain: true

production:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_api_secret
  secure: true
  cdn_subdomain: true
